# windows XP test target
#
#  This ini was created for testing windows XP targets.  
#
[ENV]
RESIM_TARGET=board
INIT_SCRIPT=mapdriver.simics
#CREATE_RESIM_PARAMS=YES
#RUN_FROM_SNAP=running2
#RUN_FROM_SNAP=aboutToProc
#RUN_FROM_SNAP=pending2
RUN_FROM_SNAP=ssh_running_again

[board]
$host_name=board
$use_disk2=FALSE
$use_disk3=FALSE
$disk_image=$RESIM_IMAGE/windowsXP/board.disk0.hd_image.craff
$disk_size=10737418240
$mac_address_0="00:E2:27:0F:CA:A9"
$mac_address_1="00:E1:27:0F:CA:A8"
$mac_address_2="00:1A:A0:E1:1C:9F"
$mac_address_3="00:bA:A0:E1:1C:9F"

$create_network=switch1
$create_disk0="ide"
$create_cdrom="ide"
#$iso_image=$RESIM_IMAGE/windowsXP/en_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-73974.iso
$iso_image=$RESIM_IMAGE/windowsXP/cd.iso
$eth_dev=dec21041
#$eth_dev=i82546bg

SIMICS_SCRIPT=x86-x58-ich10/genx86.simics
OS_TYPE=WINXP
RESIM_PARAM=winxp.param
RESIM_UNISTD=$RESIM_DIR/linux/ia32_generated/unistd_32_ia32.h
RESIM_ROOT_PREFIX=$RESIM_IMAGE/windowsXP/cdrive2

BOOT_CHUNKS=90000000
#ONLY_PROGS=winxp.only
ETH1_SWITCH=NONE
ETH2_SWITCH=switch1
SKIP_PROGS=winxp2.ignore
SYSTEM_CALL_MAP=xp-calls.json

[driver]
SIMICS_SCRIPT=x86-x58-ich10/genx86.simics
$host_name=driver
$use_disk2=FALSE
$use_disk3=FALSE
$disk_image=$RESIM_IMAGE/driver/driver_22.disk0.hd_image.craff
$disk_size=21496236544

#$eth_dev=i82546bg
$eth_dev=i82559

$mac_address_0="00:E1:27:0F:CA:A9"
$mac_address_1="00:E1:27:0F:CA:A8"
$mac_address_2="00:1A:A0:E1:1C:9F"
$mac_address_3="00:1A:A0:E1:1C:A0"
#ETH0_SWITCH=switch2
#ETH2_SWITCH=switch0
